### ISSUE TITLE
Documentation Out Of Date

### ISSUE THREAD

**Issue by briananderson1222** [artikcloud/artikcloud-js#2]
Individual API Docs are Out of Date.. Reference `require('artik-cloud-api')` and `ApiClient.default` --> `ApiClient.instance`. Also, for some reason my calls to `getUserDevices` in the UsersApi always gives me back an empty `devices: []` list even when Online Console returns results..

**Comment by yujingwu** [comment]
@maneeshsahu 

Could you please look at this?

**Comment by briananderson1222** [comment]
I'll provide more in depth information tomorrow about specifically what
I've noticed. Sorry for the messy messaging, but thanks for the quick
response.

**Comment by maneeshsahu** [comment]
@briananderson1222 Till we fix the doc, can you look at the UserApi tests for usage? https://github.com/artikcloud/artikcloud-js/blob/master/test/api/UsersApiTest.js

**Comment by briananderson1222** [comment]
Disregard the issue with `getUserDevices` as I think it was actually a oauth scope issue. As far as the documentation goes.. Didn't know if this would help: https://github.com/artikcloud/artikcloud-js/pull/3

**Comment by maneeshsahu** [comment]
Fixed in 2.0.1. https://github.com/artikcloud/artikcloud-js/releases/tag/2.0.1
