### ISSUE TITLE
ApiClient.default is undefined

### ISSUE THREAD

**Issue by jonathanpaek** [artikcloud/artikcloud-js#4]
ApiClient.default is undefined which is needed to initiate any api calls.

Undefined here:

``` javascript
var defaultClient = ArtikCloud.ApiClient.default;
```

Error:

``` bash
var artikcloud_oauth = defaultClient.authentications['artikcloud_oauth'];
                                    ^
TypeError: Cannot read property 'authentications' of undefined
    at Object.<anonymous> (<Redacted>/nodejs/starter.js:6:37)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It looks like there is 'instance' available on ApiClient and should read:

``` javascript
var defaultClient = ArtikCloud.APIClient.instance
```

Any plans on providing a different client?  If not will PR changes for next release.

**Comment by rzr** [comment]
I also observed this on current version

**Comment by yujingwu** [comment]
@jonathanpaek  please create a DX JIRA ticket for this. Otherwise, it is not on anyone's radar and wont be fixed.

**Comment by orchestor** [comment]
Change 

var defaultClient = ArtikCloud.ApiClient.**default**; 

to 


var defaultClient = ArtikCloud.ApiClient.**instance**;


works. please update the example.

**Comment by wenboo** [comment]
I also meet this issue and @orchestor 's method is OK. We hope it'll be sync to the github soon. Thanks.
