### ISSUE TITLE
Client Credentials method

### ISSUE THREAD

**Issue by fud** [artikcloud/artikcloud-js#8]
Hi,

I don't think this library has the ability to do the clients credentials method as outlined here,

https://developer.artik.cloud/documentation/getting-started/authentication.html#client-credentials-method

My code is server side node.js (not client site), so I don't want to have to use oauth and want to use my application tokens.

**Comment by yujingwu** [comment]
So far SDKs do not support OAuth flow. Client Credentials is one of OAuth methods. 
We are looking to support OAuth in SDKs. However, there is no timeline to share at this point.
