### ISSUE TITLE
Doing a getAllSubscriptions call payload doesn't match data returned

### ISSUE THREAD

**Issue by fud** [artikcloud/artikcloud-js#9]
I'm doing a call to get all the subscriptions along the lines of,

```
var subscriptionsApi = new ArtikCloud.SubscriptionsApi();
subscriptionsApi.getAllSubscriptions({}, callback);
```

But the payload returned does not match what the library code expects. 

Payload returned

``` [ { id: 'xx',
    aid: 'xx',
    messageType: 'message',
    uid: 'xx',
    sdtid: 'xx',
    description: 'Send messages from Artik to Kinesis',
    subscriptionType: 'xx',
    awsKey: 'xx',
    awsRegion: 'ap-southeast-1',
    awsKinesisStreamName: 'xx',
    status: 'ACTIVE',
    createdOn: 1503532007218,
    modifiedOn: 1503532007218 } ]
```
https://github.com/artikcloud/artikcloud-js/blob/master/src/model/SubscriptionArray.js#L46

This line is expecting a 'subscriptions' property but the payload does not have that property, it's just an array of objects.

**Comment by yujingwu** [comment]
Thanks for reporting this. We will look into it.

**Comment by jonathanpaek** [comment]
@fud thanks for sending.   In the json response you provided, I'm interested in seeing the 'parent' keys that was cutoff.   Could you share this?   Specifically, the 2nd parameter `data` parameter from the callback:

```javascript
var callback = function(error, data, response) {
   console.log(JSON.stringify(data));
} 
```

Can you confirm something like the following.   Array wrapped by a "data" key.
```
{
   "data":[
      {
         "id":"1673d7394737480d847023acfc50c9d",
         ...
      },
      {
         "id":"7dfb1e6290e848d9b798079651df11d",
         ...
      }
   ],
   "total":2,
   "offset":0,
   "count":2
}
```

**Comment by fud** [comment]
FYI, I debugged by doing an output of console.log(response.res.text); Because at that stage the data has been unpacked through the subscriptionsApi.getAllSubscriptions call.

```
{
    "count": 1,
    "data": [
        {
            "aid": "691e4cd494164c48bcec989827accc58",
            "awsKey": "xx",
            "awsKinesisStreamName": "xx",
            "awsRegion": "ap-southeast-2",
            "createdOn": 1503532007218,
            "description": "Send messages from Artik to Kinesis",
            "id": "39214c5abd5b432e9c416ea3493d21e8",
            "messageType": "message",
            "modifiedOn": 1503532007218,
            "sdtid": "dtea63cceab0a44c83b29c714bb79ee51e",
            "status": "ACTIVE",
            "subscriptionType": "awsKinesis",
            "uid": "b7a08456a8474cb9b226d0e7f1e6a22b"
        }
    ],
    "offset": 0,
    "total": 1
}
```

**Comment by jonathanpaek** [comment]
@fud  - thank you for confirming and the quick response.   Team has discussed issue —  at this time fix is planned to change `SubscriptionArray.js` (and other similar issue) to conform based on the HTTP response.   Fix is planned for next release.

```javascript
//SubscriptionArray.js
 if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Subscription]);
 }
```
